env:
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - never
  no-unused-vars:
    - warn
    - all
  for-direction:
    - error
  no-await-in-loop:
    - error
